import React from 'react';
import Head from 'next/head';

interface HeaderTitles {
    siteTitle: any;
    siteExtra: string | undefined;
}

const Header = (props: HeaderTitles) => {
  let titleGenerated: string = props.siteTitle;
  if (props.siteExtra !== undefined || props.siteExtra === '' ) {
    titleGenerated += ' ' + props.siteExtra;
  }

  return (
    <Head>
        <title>{titleGenerated}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Header;